
#inputFileName: "/data/galucia/lithium_local/same/LHC23_PbPb_pass5_same.root"
#inputFileName: "/data/galucia/lithium_local/same/LHC24_PbPb_pass2_same.root"
#inputFileName: "/data/galucia/lithium_local/same/LHC23_PbPb_pass4_all_same.root"
inputFileName: "/data/galucia/lithium_local/same/LHC24ar_pass1_hadronpid_same.root"

#outputFileName: "/data/galucia/lithium_local/mixing/LHC23_PbPb_pass5_event_mixing_batch105.root"
#outputFileName: "/data/galucia/lithium_local/mixing/LHC23_PbPb_pass5_rotation_mixing.root"
#outputFileName: "/data/galucia/lithium_local/mixing/LHC23_PbPb_pass4_all_event_mixing_batch105.root"
#outputFileName: "/data/galucia/lithium_local/mixing/LHC24_PbPb_pass2_event_mixing_batch105.root"
#outputFileName: "/data/galucia/lithium_local/mixing/LHC24_PbPb_pass2_rotation_mixing.root"
outputFileName: "/data/galucia/lithium_local/mixing/LHC24ar_pass1_hadronpid_event_mixing_batch256_reject_multiples.root"

doMerge: true

inputCands: "output/inputCands_24.root"
inputColls: "output/inputColls_24.root"

mixingStrategy: 0 # 0: event mixing, 1: angle mixing
mixingDepth: 10
randomSeed: 256
is23: false
applyCuts: true
